# Auxiliar 0: Ambiente de trabajo 💻</h1>
**Procesamiento de Lenguaje Natural (CC6205-1 - Otoño 2024)**

<h3><b>📚Objetivo del auxiliar<b>📚<h3>

La clase auxiliar de esta semana tendrá los siguientes objetivos:

1. Introducción a Google Colab y Markdown:
  - Entorno de Google Colab y sus capacidades, incluyendo el acceso a GPU, manejo de memoria RAM y almacenamiento en la nube.
  - Conceptos básicos de Markdown para la creación de documentos estructurados y formateados.

2. Introducción a NumPy:
  - Crear, manipular y operar con arreglos multidimensionales utilizando NumPy.
  - Creación de arreglos, cambio de forma, operaciones básicas y slicing.

3. Introducción a Pandas:
  - Manejo de datos tabulares utilizando Pandas.
  - Creación de Series y DataFrames, lectura de datos desde diferentes fuentes, y operaciones básicas de selección y filtrado.

4. Introducción a NLTK:
  - Procesamiento de lenguaje natural utilizando NLTK.
  - Técnicas como tokenización, stemming y lematización para el análisis de texto.

Para validar que ha logrado los objetivo del auxiliar se le recomienda realizar los ejercicios.

*Recomendación: Una vez resuelto, pueden utilizar cualquier parte del código que les parezca prudente para futuras tareas 😊.*

# Pequeña introducción a Colab y Markdown

**Google Colab** es una herramienta para la enseñanza e investigación de Machine Learning. Es un entorno de Jupyter notebook que no requiere configuración para su uso. **Colab** ofrece un servicio gratuito de GPU en la nube alojado por Google para alentar la colaboración en el campo de Machine Learning, sin preocuparse por los requisitos de hardware. **Colab** fue lanzado al público por Google en octubre de 2017.

## Ejercicio 0


Para iniciar puedes crear una copia del notebook en tu Drive en **File -> Save a copy in Drive**. Tambien puedes descargar el notebook como archivo ```.ipynb``` en local o compartir el enlace del notebook en Drive con algun estudiante de la clase.

Agregar tu nombre en la celda de abajo siguiendo los siguintes pasos:
1. Has doble click en la celda
2. Cambia \*\*agrega aqui tu nombre\*\* por tu nombre

Mi nombre es **agrega aqui tu nombre**.

## Markdown

**Markdown** es un lenguaje de marcado ligero creado por *John Gruber* que trata de conseguir la **máxima legibilidad** y **facilidad** de publicación.

Esto es un parrafo, `esto esta en codigo`, **esto esta en negrita**, *esto esta en cursiva*

Se puede insertar codigo multilinea tambien.

```python
print("hello world!")
```

Se pueden insertar lineas para separar texto

---

Se pueden insertar tablas!

| 0,1       | 0,2  | 0,3  | 0,4   | 0,5     |
|-----------|------|------|-------|---------|
| 1,1       | 1,2  | 1,3  | 1,4   | 1,5     |
| 2,1       | 2,2  | 2,3  | 2,4   | 2,5     |

Se puede "citar" texto usando cabezas de pescado
> Esta es una frase celebre de algun famoso
>
> -- Albert Einstein

Tambien se puede insertar formulas de $\LaTeX$ dentro del mismo texto: $a = \frac{e^y\sqrt{x+2}}{x^2}$. Se puede insertar $\LaTeX$ en general tambien.

\begin{equation}
\it{CE}(p,q)=\sum_{x}p(x)\log \bigg(\frac{1}{q(x)}\bigg)=- \sum_{x}p(x)\log q(x)
\end{equation}

Tambien se puede escribir `html`.

<strong> Esto esta en negrita usando html </strong>

Aca dejo mas recursos sobre Markdown, Colab y Jupyter Notebook:
* https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax
* https://es.wikipedia.org/wiki/Markdown
* https://colab.research.google.com/notebooks/intro.ipynb
* https://jupyter.org/
* https://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Cell%20Magics.ipynb

### Ejercicio 1

Escribe un breve texto utilizando Markdown que contenga lo siguiente:

* Un título principal que diga "NLP es genial!"
* Un ejemplo de código en Python dentro de un bloque de código, que imprima "Hola, Markdown!".
* Una tabla simple con al menos dos filas y dos columnas.
* Una cita famosa que te inspire.
* Un enlace al repositorio del curso.

## GPU/RAM/Almacenamiento/Google Drive/Clonando repo
En Colab, obtendrá **12 horas de tiempo de ejecución**, pero la sesión se desconectará si está inactivo durante más de 60 minutos. Esto significa que por cada 12 horas, el disco, la RAM, la memoria caché de la CPU y los datos que se encuentran en nuestra máquina virtual asignada se **borrarán**.

Para habilitar el uso del acelerador de hardware GPU, solo es necesario ir a **Runtime -> Change runtime type -> Hardware accelerator -> GPU** (En español se puede encontrar en **Entorno de ejecución -> Cambiar tipo de entorno de ejecución -> Acelerador por hardware -> GPU**

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!nvidia-smi --query-gpu=memory.total,memory.used,memory.free --format=csv

/bin/bash: line 1: nvidia-smi: command not found


RAM

In [ ]:
!free -h

               total        used        free      shared  buff/cache   available
Mem:            12Gi       933Mi       7.3Gi       7.0Mi       4.5Gi        11Gi
Swap:             0B          0B          0B


Almacenamiento

In [ ]:
!df -h --total | grep Filesystem
!df -h --total | grep total

Filesystem      Size  Used Avail Use% Mounted on
total           211G   75G  136G  36% -


Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Clonando repo

In [ ]:
import os

if not os.path.exists('/content/CC6205'):
  !git clone https://github.com/dccuchile/CC6205.git

### Ejercicio 2

Supongamos que estás trabajando en un proyecto en Google Colab y necesitas utilizar recursos como la GPU, RAM, almacenamiento, Google Drive y clonar un repositorio.

Escribe un breve texto que contenga lo siguiente:

* Explica por qué es importante habilitar el uso del acelerador de hardware GPU en Google Colab.
* Proporciona un ejemplo de cómo puedes verificar la cantidad de memoria disponible en la GPU.
* Explica cómo puedes verificar la cantidad de RAM disponible en Google Colab.
* Describe cómo puedes verificar la cantidad de almacenamiento disponible en la máquina virtual de Google Colab.
* Explica cómo puedes montar Google Drive en Google Colab y por qué esto puede ser útil.
* Explica cómo puedes clonar un repositorio de GitHub en Google Colab.
* Investiga que hacen los comandos ```!ls``` y ```!pwd``` en una celda de codigo.

# Pequeña introducción a Numpy, Pandas y NLTK

Colab viene con muchas librerias preinstaldas.
Entre las que más usaremos en este curso se encuentran:
- [NumPy](https://numpy.org/)
- [pandas](https://pandas.pydata.org/).

La documentación de estas librerías la pueden encontrar en estos enlaces.
* https://pandas.pydata.org/docs/
* https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
* https://numpy.org/doc/1.18/
* https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf



## NumPy

Paquete fundamental para computación matemática.

**Clase principal:** arreglo n-dimensional, `ndarray`

In [ ]:
import numpy as np
np.__version__

'1.25.2'

### Creación básica de arreglos

Creando e imprimiendo arreglos de numpy (ndarray):
- las matrices unidimensionales se imprimen luego como filas,
- las bidimensionales como matrices y tridimensionales como listas de matrices.

In [ ]:
# Crear un arreglo a partir de una lista de listas
print("Arreglo a partir de una lista de listas:")
print(np.array([[1., 0., 0.], [0., 1., 2.]]), "\n")

# Crear un arreglo de ceros
print("Arreglo de ceros:")
print(np.zeros(10), "\n")

# Crear un arreglo de ceros multidimensional
a = np.zeros((2, 3, 4))
print("Arreglo multidimensional de ceros:")
print(a, "\n")

# Crear un arreglo de unos
print("Arreglo de unos:")
print(np.ones(10), "\n")

# Crear un arreglo de unos multidimensional con tipo de datos especificado
b = np.ones((2, 3, 4), dtype='int')
print("Arreglo multidimensional de unos:")
print(b, "\n")

# Crear un arreglo de valores aleatorios entre 0 y 1
print("Arreglo de valores aleatorios:")
print(np.random.rand(5), "\n")

# Crear un arreglo multidimensional de valores aleatorios entre 0 y 1
c = np.random.rand(2, 3, 4)
print("Arreglo multidimensional de valores aleatorios:")
print(c, "\n")

Arreglo a partir de una lista de listas:
[[1. 0. 0.]
 [0. 1. 2.]] 

Arreglo de ceros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Arreglo multidimensional de ceros:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 

Arreglo de unos:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

Arreglo multidimensional de unos:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

Arreglo de valores aleatorios:
[0.89503501 0.23778486 0.9952165  0.65178925 0.13496444] 

Arreglo multidimensional de valores aleatorios:
[[[0.42741275 0.19374563 0.70583744 0.52944995]
  [0.49033345 0.52136969 0.01594154 0.96335687]
  [0.46141878 0.56190716 0.50315863 0.97222422]]

 [[0.6139446  0.45032757 0.10066418 0.05224033]
  [0.04105996 0.02376666 0.04911838 0.64749572]
  [0.56863661 0.82600304 0.74722521 0.86550548]]] 



Los atributos más importantes de un objeto ndarray son:

In [ ]:
# Número de dimensiones del arreglo
print("Número de dimensiones del arreglo:", c.ndim)

# Forma del arreglo (tamaño en cada dimensión)
print("Forma del arreglo (tamaño en cada dimensión):", c.shape)

# Número total de elementos en el arreglo
print("Número total de elementos en el arreglo:", c.size)

# Tipo de datos de los elementos del arreglo
print("Tipo de datos de los elementos del arreglo:", c.dtype)

Número de dimensiones del arreglo: 3
Forma del arreglo (tamaño en cada dimensión): (2, 3, 4)
Número total de elementos en el arreglo: 24
Tipo de datos de los elementos del arreglo: float64


Creando arreglos a partir de sequencias de numeros

In [ ]:
# Crear un arreglo de enteros en un rango especificado
print("Arreglo de enteros en un rango especificado:")
print(np.arange(10), "\n")

# Crear un arreglo de enteros en un rango especificado con un paso determinado
print("Arreglo de enteros en un rango especificado con un paso determinado:")
print(np.arange(3, 20, 2), "\n")

# Crear un arreglo con 5 números equidistantes entre 1 y 2
print("Arreglo con 5 números entre 1 y 2:")
print(np.linspace(1, 2, 5), "\n")

Arreglo de enteros en un rango especificado:
[0 1 2 3 4 5 6 7 8 9] 

Arreglo de enteros en un rango especificado con un paso determinado:
[ 3  5  7  9 11 13 15 17 19] 

Arreglo con 5 números entre 1 y 2:
[1.   1.25 1.5  1.75 2.  ] 



In [ ]:
# Cambiando las dimensiones de un array (ravel, reshape, resize)

# Utilizar 'ravel' para aplanar el arreglo a una dimensión
d = c.ravel()
print("Arreglo aplanado:", d, "\n")
print("Forma del arreglo aplanado:", d.shape, "\n")
print("Forma del arreglo original:", c.shape, "\n")

# Utilizar 'reshape' para crear un nuevo arreglo con otra distribución de las dimensiones (no modifica el original)
d = c.reshape((2, 12))
print("Nuevo arreglo con otra distribución de las dimensiones:", d, "\n")
print("Forma del nuevo arreglo:", d.shape, "\n")

# Utilizar 'T' para crear un nuevo arreglo con la transpuesta
e = d.T
print("Nuevo arreglo con la transpuesta:", e, "\n")
print("Forma del nuevo arreglo con la transpuesta:", e.shape, "\n")

# Utilizar 'resize' para cambiar las dimensiones en el propio arreglo (modifica el original)
x = d.resize(2, 12)
print("Forma del arreglo modificado:", d.shape, "\n")
print("Valor devuelto por resize (None indica que el arreglo fue modificado in-place):", x)

Arreglo aplanado: [0.42741275 0.19374563 0.70583744 0.52944995 0.49033345 0.52136969
 0.01594154 0.96335687 0.46141878 0.56190716 0.50315863 0.97222422
 0.6139446  0.45032757 0.10066418 0.05224033 0.04105996 0.02376666
 0.04911838 0.64749572 0.56863661 0.82600304 0.74722521 0.86550548] 

Forma del arreglo aplanado: (24,) 

Forma del arreglo original: (2, 3, 4) 

Nuevo arreglo con otra distribución de las dimensiones: [[0.42741275 0.19374563 0.70583744 0.52944995 0.49033345 0.52136969
  0.01594154 0.96335687 0.46141878 0.56190716 0.50315863 0.97222422]
 [0.6139446  0.45032757 0.10066418 0.05224033 0.04105996 0.02376666
  0.04911838 0.64749572 0.56863661 0.82600304 0.74722521 0.86550548]] 

Forma del nuevo arreglo: (2, 12) 

Nuevo arreglo con la transpuesta: [[0.42741275 0.6139446 ]
 [0.19374563 0.45032757]
 [0.70583744 0.10066418]
 [0.52944995 0.05224033]
 [0.49033345 0.04105996]
 [0.52136969 0.02376666]
 [0.01594154 0.04911838]
 [0.96335687 0.64749572]
 [0.46141878 0.56863661]
 [0.5619

In [ ]:
# Crear un arreglo de unos con dimensiones similares a otro arreglo
b = np.ones_like(a)
print("Arreglo de unos con dimensiones similares a 'a':")
print(b, "\n")
print("Forma del arreglo 'b':", b.shape, "\n")

# Crear un arreglo vacío con dimensiones similares a otro arreglo
c = np.empty(a.shape)
print("Arreglo vacío con dimensiones similares a 'a':")
print(c, "\n")
print("Forma del arreglo 'c':", c.shape, "\n")

Arreglo de unos con dimensiones similares a 'a':
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 

Forma del arreglo 'b': (2, 3, 4) 

Arreglo vacío con dimensiones similares a 'a':
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 

Forma del arreglo 'c': (2, 3, 4) 



### Operaciones básicas sobre arreglos

In [ ]:
# Crear algunos arreglos con lo que hemos aprendido
a = np.arange(22, 32)
b = np.arange(11, 21)
print("Forma del arreglo 'a':", a.shape)
print("Forma del arreglo 'b':", b.shape)

Forma del arreglo 'a': (10,)
Forma del arreglo 'b': (10,)


In [ ]:
# Suma y resta de arreglos
print("Suma de arreglos 'a' y 'b':", a + b)
print("Resta de arreglos 'a' y 'b':", a - b)

# Producto punto a punto (elemento a elemento) de arreglos
print("Producto punto a punto de arreglos 'a' y 'b':", a * b)

Suma de arreglos 'a' y 'b': [33 35 37 39 41 43 45 47 49 51]
Resta de arreglos 'a' y 'b': [11 11 11 11 11 11 11 11 11 11]
Producto punto a punto de arreglos 'a' y 'b': [242 276 312 350 390 432 476 522 570 620]


In [ ]:
# Cambiar la forma del arreglo 'a' a 2x5 y del arreglo 'b' a 5x2
a.resize(2, 5)
b.resize(5, 2)

print("Arreglo 'a' con nueva forma (2x5):")
print(a)
print("\nArreglo 'b' con nueva forma (5x2):")
print(b)

Arreglo 'a' con nueva forma (2x5):
[[22 23 24 25 26]
 [27 28 29 30 31]]

Arreglo 'b' con nueva forma (5x2):
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [ ]:
# Producto matricial entre los arreglos 'a' y 'b'
print("Producto matricial entre los arreglos 'a' y 'b':")
print(a @ b)

# Otro producto matricial entre los arreglos 'a' y 'b'
print("Otro producto matricial entre los arreglos 'a' y 'b':")
print(a.dot(b))

Producto matricial entre los arreglos 'a' y 'b':
[[1820 1940]
 [2195 2340]]
Otro producto matricial entre los arreglos 'a' y 'b':
[[1820 1940]
 [2195 2340]]


In [ ]:
# Otras operaciones con los arreglos
print("Cuadrado de los elementos del arreglo 'a':")
print(a**2)

print("Parte entera de la raíz cuadrada de los elementos del arreglo 'a':")
print(np.floor(np.sqrt(a)))

print("Pi elevado a la potencia de cada elemento del arreglo 'b' menos 10:")
print(np.pi**(b-10))

Cuadrado de los elementos del arreglo 'a':
[[484 529 576 625 676]
 [729 784 841 900 961]]
Parte entera de la raíz cuadrada de los elementos del arreglo 'a':
[[4. 4. 4. 5. 5.]
 [5. 5. 5. 5. 5.]]
Pi elevado a la potencia de cada elemento del arreglo 'b' menos 10:
[[3.14159265e+00 9.86960440e+00]
 [3.10062767e+01 9.74090910e+01]
 [3.06019685e+02 9.61389194e+02]
 [3.02029323e+03 9.48853102e+03]
 [2.98090993e+04 9.36480475e+04]]


In [ ]:
# Cambiar la forma del arreglo 'b' a 2x5 y asignarlo a 'e'
e = b.reshape(2, 5)
print("Arreglo 'e' con forma (2x5):")
print(e)

# Al especificar el parámetro axis, se puede aplicar una operación a lo largo de la dimensión especificada
# En este caso, se encuentra el máximo valor a lo largo del eje 1 (a lo largo de las filas) en el arreglo 'e'
print("Máximo valor a lo largo de las filas en el arreglo 'e':")
print(e.max(axis=1))

Arreglo 'e' con forma (2x5):
[[11 12 13 14 15]
 [16 17 18 19 20]]
Máximo valor a lo largo de las filas en el arreglo 'e':
[15 20]


In [ ]:
# Cambiar un valor específico en el arreglo 'e'
e[0, 0] = 1000
print("Arreglo 'e' después de cambiar el valor en la posición (0, 0):")
print(e)

Arreglo 'e' después de cambiar el valor en la posición (0, 0):
[[1000   12   13   14   15]
 [  16   17   18   19   20]]


### Slicing

Estudio de 'slicing' con numpy

In [ ]:
# Arreglo de ejemplo
a = np.arange(18).reshape(3,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [ ]:
# Seleccionar la primera fila del arreglo 'a'
print("Primera fila del arreglo 'a':")
print(a[0, :])

Primera fila del arreglo 'a':
[0 1 2 3 4 5]


In [ ]:
# Seleccionar la segunda columna del arreglo 'a'
print("Segunda columna del arreglo 'a':")
print(a[:, 1])

Segunda columna del arreglo 'a':
[ 1  7 13]


In [ ]:
# Seleccionar el elemento en la tercera fila y cuarta columna del arreglo 'a'
print("Elemento en la tercera fila y cuarta columna del arreglo 'a':")
print(a[2, 3])

Elemento en la tercera fila y cuarta columna del arreglo 'a':
15


### Broadcasting

Muchas operaciones en NumPy soportan [Broadcasting Semantics](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting).

Si una operación NumPy admite broadcast, sus argumentos (ndarrays) se pueden expandir automáticamente para que sean del mismo tamaño (**sin hacer copias de los datos**). *No es más que una forma de hacer operaciones punto a punto sobre ndarrays que no necesariamente tienen las mismas dimensiones.*

Dos `ndarray` son "broadcastable" si:
1. Cada array tiene al menos una dimensión.
2. Al iterar sobre los tamaños de las dimensiones (comenzando en la dimensión final), sus tamaños deben ser iguales, uno de ellos es `1` o uno de ellos no existe.

Si dos `ndarray` son "broadcastable" las dimensiones del `ndarray` resultado se determina mediante:
1. Si el número de dimensiones no es igual, se antepone `1` a las dimensiones del `ndarray` con menos dimensiones para que tengan la misma longitud.
2. Luego, para cada tamaño de dimensión, el tamaño de dimensión resultante es el máximo de los tamaños en esa dimensión.

In [ ]:
# Definir los arreglos con np.random.randint
a = np.random.randint(0, 10, size=(2, 1))
b = np.random.randint(0, 10, size=(1, 8))

# Mostrar los arreglos
print("Arreglo 'a':")
print(a)
print("\nArreglo 'b':")
print(b)

# Realizar la suma y obtener la forma resultante
result = a + b

# Mostrar el resultado de la suma y su forma
print("\nResultado de la suma:")
print(result)
print("\nForma del resultado de la suma:", result.shape)

Arreglo 'a':
[[3]
 [3]]

Arreglo 'b':
[[7 8 2 3 1 6 1 5]]

Resultado de la suma:
[[10 11  5  6  4  9  4  8]
 [10 11  5  6  4  9  4  8]]

Forma del resultado de la suma: (2, 8)


El broadcasting se aplica para extender automáticamente las dimensiones de ambos arreglos de manera que sean compatibles para la operación de suma. NumPy agrega dimensiones adicionales con tamaño 1 a los arreglos que lo necesiten, permitiendo así la realización de operaciones elemento a elemento. En este caso, el resultado es un arreglo con forma (2, 8), donde cada elemento es la suma del correspondiente elemento en 'a' y 'b'.

### Ejercicio 3

En base a los ejemplo, identifique si es capaz de completar los siguientes puntos:
* Crea un arreglo de numpy que contenga una matriz unidimensional y otro que contenga una matriz bidimensional, utilizando la función np.array.
* Crea un arreglo de numpy que contenga solo valores cero, utilizando la función np.zeros.
* Crea un arreglo de numpy que contenga solo valores uno, utilizando la función np.ones.
* Genera un arreglo de numpy con valores aleatorios, utilizando la función np.random.rand.
* Utiliza la función np.arange para crear un arreglo de numpy con una secuencia de números.
* Utiliza la función np.linspace para crear un arreglo de numpy con valores espaciados de manera uniforme.
* Realiza cambios en la forma de un arreglo utilizando métodos como ravel, reshape y resize. Indentifique las diferencias.
* Realiza operaciones básicas como suma, resta, multiplicación y potenciación entre arreglos de numpy.
* Accede a elementos específicos de un arreglo utilizando técnicas de "slicing".
* Explora el concepto de "Broadcasting Semantics" en NumPy y realiza una operación que utilice broadcasting.

## Pandas

**Pandas** es una de las herramientas preferidas por cientista de datos de datos para manejar y el analizar los datos. Junto a `matplotlib` para la visualización de datos, `Pandas` está construido fundamentalmente sobre `NumPy`.

In [ ]:
import pandas as pd

# Imprimir la versión de Pandas
print("Versión de Pandas:", pd.__version__)

Versión de Pandas: 1.5.3


### Series

Arreglo uni-dimensional etiquetado, que puede contener cualquier tipo de datos.

In [ ]:
# Crear una serie de Pandas
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])

# Imprimir la serie
print(s)

a    3
b   -5
c    7
d    4
dtype: int64


### DataFrame

Estructura de datos bi-dimensional etiquetada con columnas de tipos potencialmente diferentes.

In [ ]:
# Crear el DataFrame df1
df1 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

# Imprimir el DataFrame df1
df1

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Metodo```.info()```. Este método imprime información sobre un DataFrame, incluido el tipo de índice, las columnas, los valores no nulos y el uso de la memoria.

In [ ]:
# Obtener información sobre el DataFrame df1
df1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32       
 3   D       4 non-null      int32         
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 288.0+ bytes


In [ ]:
# Datos proporcionados
data2 = [['Belgium', 'India', 'Brazil'],
         ['Brussels', 'New Delhi', 'Brasilia'],
         [11190846, 1303171035, 207847528]]

# Crear el DataFrame df2
df2 = pd.DataFrame(np.array(data2).T)

# Imprimir el DataFrame df2
df2

0          1           2
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

### Leyendo de un archivo

Descargando primero el archivo. Usando la habilidad de colab de ejecutar comandos de shell desde una celda de código, podemos descargar un dataset usando la linea de comando, ya sea con ```wget``` o ```curl```.

In [ ]:
!wget users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv

--2024-03-18 17:56:00--  http://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv
Resolving users.dcc.uchile.cl (users.dcc.uchile.cl)... 192.80.24.4, 200.9.99.211
Connecting to users.dcc.uchile.cl (users.dcc.uchile.cl)|192.80.24.4|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv [following]
--2024-03-18 17:56:00--  https://users.dcc.uchile.cl/~gchapero/datasets/2018_emol_comments_small.tsv
Connecting to users.dcc.uchile.cl (users.dcc.uchile.cl)|192.80.24.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11115406 (11M) [text/tab-separated-values]
Saving to: ‘2018_emol_comments_small.tsv’

2018_emol_comments_ 100%[===================>]  10.60M  6.14MB/s    in 1.7s    

2024-03-18 17:56:02 (6.14 MB/s) - ‘2018_emol_comments_small.tsv’ saved [11115406/11115406]



In [ ]:
df = pd.read_csv("2018_emol_comments_small.tsv", delimiter="\t")
df.head()

idNoticia  idComment  creatorId   parentId  banned authSource  \
0     892722    4799147     160736        NaN   False   facebook   
1     892722    4798886       7823        NaN   False   facebook   
2     892722    4798914     245784  4798886.0   False   facebook   
3     892722    4798783      65076        NaN   False   facebook   
4     892722    4798175      11263        NaN   False   facebook   

                                                text  likes  dislikes  \
0             &nbsp;Muy bueno lo que vi del frstival      2         1   
1  &nbsp;Improvisando y con cero libreto..ajiaj e...      8         0   
2  &nbsp;@Rodrigo Cancino Sandoval[7823]&nbsp;ese...      5         2   
3        &nbsp;Avello es un adelantado, genial&nbsp;     14         1   
4  &nbsp;Su humor improvisado me pareció genial y...     15        14   

   denounces           time  level  
0          0  1516963115000      0  
1          0  1516960895000      0  
2          0  1516961099000      1  
3          0  1516959790000      0  
4          0  1516951826000      0

Desde un archivo del drive

In [ ]:
# Cargar un archivo TSV en un DataFrame
df = pd.read_csv("2018_emol_comments_small.tsv", delimiter="\t")

# Imprimir información sobre el DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42120 entries, 0 to 42119
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   idNoticia   42120 non-null  int64  
 1   idComment   42120 non-null  int64  
 2   creatorId   42120 non-null  int64  
 3   parentId    21373 non-null  float64
 4   banned      42120 non-null  bool   
 5   authSource  42120 non-null  object 
 6   text        42120 non-null  object 
 7   likes       42120 non-null  int64  
 8   dislikes    42120 non-null  int64  
 9   denounces   42120 non-null  int64  
 10  time        42120 non-null  int64  
 11  level       42120 non-null  int64  
dtypes: bool(1), float64(1), int64(8), object(2)
memory usage: 3.6+ MB


Metodo ```.head()```. Esta función devuelve las primeras n filas del objeto según la posición. Es útil para probar rápidamente si su objeto tiene el tipo correcto de datos.

In [ ]:
# Mostrar las primeras 5 filas del DataFrame (n=5)
df.head()

idNoticia  idComment  creatorId   parentId  banned authSource  \
0     892722    4799147     160736        NaN   False   facebook   
1     892722    4798886       7823        NaN   False   facebook   
2     892722    4798914     245784  4798886.0   False   facebook   
3     892722    4798783      65076        NaN   False   facebook   
4     892722    4798175      11263        NaN   False   facebook   

                                                text  likes  dislikes  \
0             &nbsp;Muy bueno lo que vi del frstival      2         1   
1  &nbsp;Improvisando y con cero libreto..ajiaj e...      8         0   
2  &nbsp;@Rodrigo Cancino Sandoval[7823]&nbsp;ese...      5         2   
3        &nbsp;Avello es un adelantado, genial&nbsp;     14         1   
4  &nbsp;Su humor improvisado me pareció genial y...     15        14   

   denounces           time  level  
0          0  1516963115000      0  
1          0  1516960895000      0  
2          0  1516961099000      1  
3          0  1516959790000      0  
4          0  1516951826000      0

In [ ]:
# Mostrar las primeras 10 filas del DataFrame
df.head(10)

idNoticia  idComment  creatorId   parentId  banned authSource  \
0     892722    4799147     160736        NaN   False   facebook   
1     892722    4798886       7823        NaN   False   facebook   
2     892722    4798914     245784  4798886.0   False   facebook   
3     892722    4798783      65076        NaN   False   facebook   
4     892722    4798175      11263        NaN   False   facebook   
5     892722    4801868     849197        NaN   False   facebook   
6     892722    4801403     449897        NaN   False   facebook   
7     892722    4800246     966973        NaN   False   facebook   
8     892722    4799366       4611        NaN   False   facebook   
9     892722    4799253     158548        NaN   False   facebook   

                                                text  likes  dislikes  \
0             &nbsp;Muy bueno lo que vi del frstival      2         1   
1  &nbsp;Improvisando y con cero libreto..ajiaj e...      8         0   
2  &nbsp;@Rodrigo Cancino Sandoval[7823]&nbsp;ese...      5         2   
3        &nbsp;Avello es un adelantado, genial&nbsp;     14         1   
4  &nbsp;Su humor improvisado me pareció genial y...     15        14   
5  &nbsp;Felipe Avello notable me reí mucho con s...      1         0   
6  &nbsp;ESTAN MATANDO A UN WUEONNNN....... notab...      2         0   
7  &nbsp;este tipo es un adelantado, es como anti...      1         0   
8  &nbsp;Verdaderamente lo más grosero por su asp...      1         2   
9  &nbsp;felipe avello es un gran ejemplo para qu...      1         7   

   denounces           time  level  
0          0  1516963115000      0  
1          0  1516960895000      0  
2          0  1516961099000      1  
3          0  1516959790000      0  
4          0  1516951826000      0  
5          0  1516985109000      0  
6          0  1516981306000      0  
7          0  1516971463000      0  
8          0  1516964930000      0  
9          0  1516963914000      0

In [ ]:
# Mostrar todas las filas excepto las últimas 3 filas del DataFrame
df.head(-3)

idNoticia  idComment  creatorId   parentId  banned authSource  \
0         892722    4799147     160736        NaN   False   facebook   
1         892722    4798886       7823        NaN   False   facebook   
2         892722    4798914     245784  4798886.0   False   facebook   
3         892722    4798783      65076        NaN   False   facebook   
4         892722    4798175      11263        NaN   False   facebook   
...          ...        ...        ...        ...     ...        ...   
42112     890250    4681378       1023  4680261.0   False   facebook   
42113     890250    4681513       6238  4681378.0   False   facebook   
42114     890250    4682344       1023  4681378.0   False   facebook   
42115     890250    4697770       5644  4680261.0   False   facebook   
42116     890250    4680095       1535        NaN   False   facebook   

                                                    text  likes  dislikes  \
0                 &nbsp;Muy bueno lo que vi del frstival      2         1   
1      &nbsp;Improvisando y con cero libreto..ajiaj e...      8         0   
2      &nbsp;@Rodrigo Cancino Sandoval[7823]&nbsp;ese...      5         2   
3            &nbsp;Avello es un adelantado, genial&nbsp;     14         1   
4      &nbsp;Su humor improvisado me pareció genial y...     15        14   
...                                                  ...    ...       ...   
42112  &nbsp;@Javier Perez[962] Hay que mencionar que...      1         0   
42113  &nbsp;@Rene Alexander Alvarez[1023]&nbsp;Bater...      1         0   
42114  &nbsp;@Rene Alexander Alvarez[1023] Las baterí...      1         0   
42115  &nbsp;@Javier Perez[962]&nbsp;lea esto&nbsp;ht...      0         0   
42116  &nbsp;Habrá que verlo cuando esté listo y en v...      1         0   

       denounces           time  level  
0              0  1516963115000      0  
1              0  1516960895000      0  
2              0  1516961099000      1  
3              0  1516959790000      0  
4              0  1516951826000      0  
...          ...            ...    ...  
42112          0  1515408102000      1  
42113          0  1515409336000      2  
42114          0  1515415158000      2  
42115          0  1515593990000      1  
42116          0  1515393215000      0  

[42117 rows x 12 columns]

Desde la url directamente

In [ ]:
# Cargar el conjunto de datos desde el archivo JSON
dataset = pd.read_json('https://github.com/dccuchile/CC6205/releases/download/Data/biobio_nacional.json')

# Imprimir el tipo de dataset
print("Tipo de dataset:", type(dataset))

# Imprimir la forma del dataset
print("Forma del dataset:", dataset.shape)

# Mostrar las primeras 10 filas del dataset
dataset.head(10)

Tipo de dataset: <class 'pandas.core.frame.DataFrame'>
Forma del dataset: (200, 11)


publication_date publication_hour              author  \
0       05/08/2019            10:50   Gonzalo Cifuentes   
1       05/08/2019            07:51      Felipe Delgado   
2       05/08/2019            08:14       Nicolás Parra   
3       05/08/2019            08:19       Catalina Díaz   
4       05/08/2019            08:27       Catalina Díaz   
5       05/08/2019            08:40  Valentina González   
6       05/08/2019            08:44         Emilio Lara   
7       05/08/2019            08:44       Nicolás Parra   
8       05/08/2019            09:07  Valentina González   
9       05/08/2019            09:18   Gonzalo Cifuentes   

                   author_link  \
0    /lista/autores/gcifuentes   
1      /lista/autores/fdelgado   
2        /lista/autores/nparra   
3  /lista/autores/catalinadiaz   
4  /lista/autores/catalinadiaz   
5     /lista/autores/vgonzalez   
6         /lista/autores/elara   
7        /lista/autores/nparra   
8     /lista/autores/vgonzalez   
9    /lista/autores/gcifuentes   

                                               title  \
0  ¿Lavar la ropa con luz?: invento de chilenos e...   
1  Alrededor de 40 mil hogares de Puente Alto, Pi...   
2  Habla director de Compin Bío Bío que se autoap...   
3  6 damnificados dejó incendio que destruyó una ...   
4  Con arresto domiciliario quedó menor detenido ...   
5  Santiago buscará que el Instituto Nacional com...   
6  Crisis interna del PS gatilla renuncia de 291 ...   
7  Organizaciones proponen innovador método para ...   
8  Objeto sospechoso obligó a cerrar estación de ...   
9  Peritajes al cuerpo de Cangri revelaron presen...   

                                                link  category  \
0  https://www.biobiochile.cl/noticias/nacional/c...  Nacional   
1  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
2  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
3  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
4  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
5  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
6  https://www.biobiochile.cl/noticias/nacional/c...  Nacional   
7  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
8  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
9  https://www.biobiochile.cl/noticias/nacional/r...  Nacional   

             subcategory                                            content  \
0               Nacional    Alumnos de Ingeniería de la Universidad Cató...   
1   Región Metropolitana    Alrededor de 40 mil hogares de las comunas d...   
2     Región del Bío Bío    Quien fuera el director de la Compin Bío Bío...   
3     Región de los Ríos    Seis damnificados es el saldo de un incendio...   
4    Región de los Lagos    Con arresto domiciliario total quedó el adol...   
5   Región Metropolitana    El alcalde de Santiago, Felipe Alessandri, d...   
6               Nacional    291 militantes renunciaron al Partido Social...   
7   Región de Valparaíso    Organizaciones sociales y vecinos de Santa I...   
8   Región Metropolitana    La mañana de este lunes la presencia de un o...   
9  Región de Antofagasta    En febrero se produjeron las muertes de Seba...   

                                                tags  \
0  [#Chile, #Ingeniería UC, #LightWash, #Luz, #Se...   
1  [#Pirque, #Puente Alto, #Región Metropolitana,...   
2  [#Compin, #Concepción, #Licencia, #Region del ...   
3  [#Bomberos, #Damnificados, #Daños, #Incendio, ...   
4  [#Arresto Domiciliario, #Bullying, #Calbuco, #...   
5  [#Felipe Alessandri, #Instituto Nacional, #Lic...   
6  [#Narcotráfico, #Partido Socialista, #PS, #Ser...   
7  [#inmobiliaria, #Las salinas, #Región de Valpa...   
8  [#cosmetiquero, #estación Camino Agrícola, #Lí...   
9  [#Antofagasta, #Cangri, #Muerte, #Región de An...   

                                      embedded_links  
0                                                 []  
1                                   

### Selección

In [ ]:
# Obtener el elemento asociado con la etiqueta de índice 'b' en la Serie 's'
print("Elemento asociado con la etiqueta de índice 'b':", s['b'])

Elemento asociado con la etiqueta de índice 'b': -5


In [ ]:
# Obtener las filas de la 100 a la 119 (inclusive) del DataFrame df
subset_df = df[100:120]
subset_df

idNoticia  idComment  creatorId  parentId  banned authSource  \
100     889728    4657098      27881       NaN   False   facebook   
101     889728    4657093      27881       NaN   False   facebook   
102     889728    4657035      27881       NaN   False   facebook   
103     889728    4656697    1056388       NaN   False   facebook   
104     889728    4656558        916       NaN   False   facebook   
105     889728    4656555        916       NaN   False   facebook   
106     889728    4656519     246129       NaN   False   facebook   
107     889728    4656518      19797       NaN   False   facebook   
108     889728    4656483      78108       NaN   False   facebook   
109     889728    4656465       8891       NaN   False   facebook   
110     889728    4655580      59984       NaN   False   facebook   
111     889728    4655460      22458       NaN   False   facebook   
112     889728    4655149      21545       NaN   False   facebook   
113     889728    4655006     424540       NaN   False   facebook   
114     889728    4654932     753331       NaN   False   facebook   
115     889728    4654683       5636       NaN   False   facebook   
116     889728    4654558    1032437       NaN   False   facebook   
117     889728    4654342     155147       NaN   False   facebook   
118     889728    4654208      74305       NaN   False   facebook   
119     889728    4654110     129584       NaN   False   facebook   

                                                  text  likes  dislikes  \
100                                             &nbsp;      0         0   
101                                             &nbsp;      0         0   
102                                             &nbsp;      0         0   
103  &nbsp;Formula E es promocionar la energia limp...      1         3   
104  &nbsp;\n<a href="http://www.emol.com/noticias/...      2         0   
105  &nbsp;esta muy bien invertir en eventos mas li...      0         0   
106  &nbsp;El Dakar no es bueno para el medi hambie...      1         1   
107  &nbsp;Estoy de acuerdo en que los dineros corr...      1         0   
108  &nbsp;Desde mi perspectiva que bien que se apo...      0         0   
109  &nbsp;Dejen el Dakar para Bolivia y Perú, apoy...      1         2   
110  &nbsp;Y dale con el ecosistema. No tienes idea...      1         1   
111             &nbsp;Tesla mira lo que has creado....      0         0   
112  &nbsp;El Dakar es un gustito que se dan alguno...      6         1   
113  &nbsp;muy simple el dakar lo único que hace es...      1         1   
114  &nbsp;Muy fácil: el Dakar es un chiste fósil a...      1         0   
115  &nbsp;Duda valida. Apoyo amabas pruebas, y sie...      0         1   
116  &nbsp;dakar vale nada,,tamarugal quebro gracia...      1         3   
117  &nbsp;Para que &nbsp;vean no se preocupen chiq...      2         0   
118  &nbsp;obvio el combustible del futuro! lo que ...      2         0   
119               &nbsp;Eliseo otro mafioso asqueroso.      4         3   

     denounces           time  level  
100          0  1515056576000      0  
101          0  1515056528000      0  
102          0  1515056141000      0  
103          0  1515051974000      0  
104          0  1515047978000      0  
105          0  1515047891000      0  
106          0  1515045957000      0  
107          0  1515045892000      0  
108          0  1515043111000      0  
109          0  1515040537000      0  
110          0  1515020660000      0  
111          0  1515019798000      0  
112          0  1515017089000      0  
113          0  1515015711000      0  
114          0  1515015027000      0  
115          0  1515012597000      0  
116          0  1515011113000      0  
117          0  1515008996000      0  
118          0  1515007899000      0  
119          0  1515007051000      0

In [ ]:
# Obtener cada d-ésima fila de las filas 100 a 119 del DataFrame df
d=2
subset_df = df.iloc[100:120:d]
subset_df

idNoticia  idComment  creatorId  parentId  banned authSource  \
100     889728    4657098      27881       NaN   False   facebook   
102     889728    4657035      27881       NaN   False   facebook   
104     889728    4656558        916       NaN   False   facebook   
106     889728    4656519     246129       NaN   False   facebook   
108     889728    4656483      78108       NaN   False   facebook   
110     889728    4655580      59984       NaN   False   facebook   
112     889728    4655149      21545       NaN   False   facebook   
114     889728    4654932     753331       NaN   False   facebook   
116     889728    4654558    1032437       NaN   False   facebook   
118     889728    4654208      74305       NaN   False   facebook   

                                                  text  likes  dislikes  \
100                                             &nbsp;      0         0   
102                                             &nbsp;      0         0   
104  &nbsp;\n<a href="http://www.emol.com/noticias/...      2         0   
106  &nbsp;El Dakar no es bueno para el medi hambie...      1         1   
108  &nbsp;Desde mi perspectiva que bien que se apo...      0         0   
110  &nbsp;Y dale con el ecosistema. No tienes idea...      1         1   
112  &nbsp;El Dakar es un gustito que se dan alguno...      6         1   
114  &nbsp;Muy fácil: el Dakar es un chiste fósil a...      1         0   
116  &nbsp;dakar vale nada,,tamarugal quebro gracia...      1         3   
118  &nbsp;obvio el combustible del futuro! lo que ...      2         0   

     denounces           time  level  
100          0  1515056576000      0  
102          0  1515056141000      0  
104          0  1515047978000      0  
106          0  1515045957000      0  
108          0  1515043111000      0  
110          0  1515020660000      0  
112          0  1515017089000      0  
114          0  1515015027000      0  
116          0  1515011113000      0  
118          0  1515007899000      0

In [ ]:
# Obtener toda la columna "author" del DataFrame dataset
authors = dataset["author"]

# Imprimir información sobre la columna "author"
print("Tipo de 'authors':", type(authors))
print("Primeras filas de 'authors':")
print(authors.head())
print("Forma de 'authors':", authors.shape)

Tipo de 'authors': <class 'pandas.core.series.Series'>
Primeras filas de 'authors':
0    Gonzalo Cifuentes
1       Felipe Delgado
2        Nicolás Parra
3        Catalina Díaz
4        Catalina Díaz
Name: author, dtype: object
Forma de 'authors': (200,)


In [ ]:
# Seleccionar las columnas "author" y "link" del DataFrame dataset
subset_df = dataset[["author", "link"]]

# Mostrar las primeras filas del DataFrame subset_df
subset_df.head()

author                                               link
0  Gonzalo Cifuentes  https://www.biobiochile.cl/noticias/nacional/c...
1     Felipe Delgado  https://www.biobiochile.cl/noticias/nacional/r...
2      Nicolás Parra  https://www.biobiochile.cl/noticias/nacional/r...
3      Catalina Díaz  https://www.biobiochile.cl/noticias/nacional/r...
4      Catalina Díaz  https://www.biobiochile.cl/noticias/nacional/r...

In [ ]:
# Crear una máscara de selección para la columna "subcategory" donde los valores sean "Nacional"
mask = dataset["subcategory"] == "Nacional"

# Imprimir información sobre la máscara de selección
print("Tipo de la máscara de selección:", type(mask), "\n")
print("Primeras filas de la máscara de selección:")
print(mask.head(), "\n")

# Seleccionar las filas del DataFrame dataset que cumplen con la máscara de selección
subset_dataset = dataset[mask]

Tipo de la máscara de selección: <class 'pandas.core.series.Series'> 

Primeras filas de la máscara de selección:
0     True
1    False
2    False
3    False
4    False
Name: subcategory, dtype: bool 



In [ ]:
# Crear una máscara de selección para la columna "subcategory" donde los valores sean "Nacional" o "Región de los Lagos"
mask = dataset["subcategory"].isin(["Nacional", "Región de los Lagos"])

# Imprimir información sobre la máscara de selección
print("Tipo de la máscara de selección:", type(mask), "\n")
print("Primeras filas de la máscara de selección:")
print(mask.head(), "\n")

Tipo de la máscara de selección: <class 'pandas.core.series.Series'> 

Primeras filas de la máscara de selección:
0     True
1    False
2    False
3    False
4     True
Name: subcategory, dtype: bool 



In [ ]:
# Aplicar la máscara de selección al DataFrame original y mostrar las primeras filas
subset_dataset = dataset[mask]
subset_dataset.head()

publication_date publication_hour             author  \
0        05/08/2019            10:50  Gonzalo Cifuentes   
4        05/08/2019            08:27      Catalina Díaz   
6        05/08/2019            08:44        Emilio Lara   
11       05/08/2019            09:50        Emilio Lara   
14       05/08/2019            10:30        Emilio Lara   

                    author_link  \
0     /lista/autores/gcifuentes   
4   /lista/autores/catalinadiaz   
6          /lista/autores/elara   
11         /lista/autores/elara   
14         /lista/autores/elara   

                                                title  \
0   ¿Lavar la ropa con luz?: invento de chilenos e...   
4   Con arresto domiciliario quedó menor detenido ...   
6   Crisis interna del PS gatilla renuncia de 291 ...   
11  Cadem: Piñera mantiene aprobación y reducción ...   
14  Senado podría votar esta semana extensión de g...   

                                                 link  category  \
0   https://www.biobiochile.cl/noticias/nacional/c...  Nacional   
4   https://www.biobiochile.cl/noticias/nacional/r...  Nacional   
6   https://www.biobiochile.cl/noticias/nacional/c...  Nacional   
11  https://www.biobiochile.cl/noticias/nacional/c...  Nacional   
14  https://www.biobiochile.cl/noticias/nacional/c...  Nacional   

            subcategory                                            content  \
0              Nacional    Alumnos de Ingeniería de la Universidad Cató...   
4   Región de los Lagos    Con arresto domiciliario total quedó el adol...   
6              Nacional    291 militantes renunciaron al Partido Social...   
11             Nacional    Los últimos resultados de la Encuesta Cadem ...   
14             Nacional    Esta semana, luego de un año y cuatro meses ...   

                                                 tags  \
0   [#Chile, #Ingeniería UC, #LightWash, #Luz, #Se...   
4   [#Arresto Domiciliario, #Bullying, #Calbuco, #...   
6   [#Narcotráfico, #Partido Socialista, #PS, #Ser...   
11  [#Cadem, #Gabinete, #Gobierno, #jornada labora...   
14     [#CFT, #Educación, #Gobierno, #Gratuidad, #IP]   

                                       embedded_links  
0                                                  []  
4   [https://media.biobiochile.cl/wp-content/uploa...  
6                                                  []  
11                                                 []  
14  [https://media.biobiochile.cl/wp-content/uploa...

In [ ]:
# Usar loc para seleccionar filas donde la columna "subcategory" es igual a "Región de los Lagos", y luego seleccionar las columnas "author", "subcategory" y "link"
subset_df = dataset.loc[dataset["subcategory"] == "Región de los Lagos", ["author", "subcategory", "link"]]

# Mostrar las primeras filas del DataFrame resultante
subset_df.head()

author          subcategory  \
4           Catalina Díaz  Región de los Lagos   
22           Nicolás Díaz  Región de los Lagos   
50  María José Villarroel  Región de los Lagos   
55          Sandar Oporto  Región de los Lagos   
59          Sandar Oporto  Región de los Lagos   

                                                 link  
4   https://www.biobiochile.cl/noticias/nacional/r...  
22  https://www.biobiochile.cl/noticias/nacional/r...  
50  https://www.biobiochile.cl/noticias/nacional/r...  
55  https://www.biobiochile.cl/noticias/nacional/r...  
59  https://www.biobiochile.cl/noticias/nacional/r...

### Ejercicio 4

Basado en la sección sobre Pandas proporcionada, resuelve lo siguiente:

* Crea una Serie de Pandas con valores y etiquetas personalizadas utilizando la función pd.Series.
* Crea un DataFrame de Pandas utilizando la función ```pd.DataFrame```, utilizando diferentes tipos de datos para las columnas.
* Utiliza el método ```.info()``` para imprimir información sobre un DataFrame.
* Lee un archivo CSV desde Google Drive utilizando la función ```pd.read_csv```.
* Utiliza el método ```.head()``` para imprimir las primeras filas de un DataFrame.
* Descarga un archivo utilizando comandos de shell (```!wget``` o ```!curl)``` y luego lee el archivo descargado en un DataFrame.
* Lee un archivo JSON desde una URL utilizando la función ```pd.read_json```
* Accede a elementos específicos de una Serie de Pandas.
* Accede a filas específicas de un DataFrame utilizando técnicas de "slicing".
* Selecciona columnas específicas de un DataFrame.
* Crea una máscara de selección utilizando una condición booleana.
* Utiliza la máscara de selección para filtrar filas en un DataFrame.
* Combina múltiples criterios de selección en un DataFrame.
* Utiliza los métodos ```.loc``` e ```.iloc``` para acceder a datos en un DataFrame. Identifique la diferencia entre los metodos.

## NLTK
**NLTK** (Natural Language Processing Kit) es una libreria de procesamiento de lenguaje natural.
Ofrece utilidades como `tokenizacion`, `lemmatization`, `stemming`, etc.


In [ ]:
# Descargar los recursos de NLTK sin ver la salida con %%capture,
%%capture
import nltk
nltk.download("all")

### Tokenization

Importar el tokenizador de palabras recomendado por NLTK (actualmente ```nltk.tokenize.treebank.TreebankWordTokenizer``` junto con ```nltk.tokenize.punkt.PunktSentenceTokenizer``` para el idioma especificado)


In [ ]:
# Importar tokenizador
from nltk import word_tokenize

# Frase de ejemplo
s = "Hola como están, esta es una frase en #español :)"

# Tokenizar la frase en español
tokens = word_tokenize(s, language="spanish")

# Mostrar los tokens resultantes
tokens

['Hola',
 'como',
 'están',
 ',',
 'esta',
 'es',
 'una',
 'frase',
 'en',
 '#',
 'español',
 ':',
 ')']

Importar otro tokenizer (pueden encontrar otros en https://www.nltk.org/api/nltk.tokenize.html)

In [ ]:
# Otro tokenizador: tokenizador de tweets
from nltk.tokenize.casual import TweetTokenizer

# Crear una instancia del tokenizador
tknzr = TweetTokenizer()

# Tokenizar la frase utilizando el tokenizador
tokens = tknzr.tokenize(s)

# Mostrar los tokens resultantes
tokens

['Hola',
 'como',
 'están',
 ',',
 'esta',
 'es',
 'una',
 'frase',
 'en',
 '#español',
 ':)']

### Stemming y Lemmatization

Importar stemmer ```SnowballStemmer``` desde NLTK. SnowballStemmer soporta los lenguajes: Arabic, Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Portuguese, Romanian, Russian, Spanish and Swedish.

In [ ]:
# Importar stemmer
from nltk.stem import SnowballStemmer

# Crear una instancia del SnowballStemmer para español
stemmer = SnowballStemmer("spanish")

# Aplicar stemming a diferentes formas de la palabra "correr"
print(stemmer.stem("corriendo"))
print(stemmer.stem("correr"))
print(stemmer.stem("corriste"))

corr
corr
corr


Stemmer en inglés

*Cuidado: las reglas de stemmer son dependientes del idioma*

In [ ]:
from nltk.stem.snowball import EnglishStemmer

# Crear una instancia del SnowballStemmer para inglés
stemmer = EnglishStemmer()

# Aplicar stemming a diferentes formas de la palabra "correr"
print(stemmer.stem("corriendo")) # no se reduce, ya que no es una palabra inglesa
print(stemmer.stem("correr"))
print(stemmer.stem("corriste"))

corriendo
correr
corrist


Usando otro stemmer (pueden encontrar otros en https://www.nltk.org/api/nltk.stem.html)

In [ ]:
from nltk.stem import PorterStemmer

# Crear una instancia del PorterStemmer
stemmer = PorterStemmer()

# Aplicar stemming a diferentes formas de la palabra "correr"
print(stemmer.stem("corriendo"))  # nuevamente no se reduce
print(stemmer.stem("correr"))
print(stemmer.stem("corriste"))

corriendo
correr
corrist


In [ ]:
# lemmatization
from nltk.stem import WordNetLemmatizer

# Crear una instancia del WordNetLemmatizer
wnl = WordNetLemmatizer()

# Lematizar algunas palabras
print(wnl.lemmatize("whale"))   # no se reduce, ya que ya es la forma base)
print(wnl.lemmatize("whales"))  # se reduce a la forma base "whale"
print(wnl.lemmatize("whaling")) # no se reduce, ya que no se encuentra en WordNet

whale
whale
whaling


### Ejercicio 5

Basado en la sección sobre NLTK proporcionada, resuelva los siguientes ejercicios:

* Utiliza la función ```word_tokenize``` de NLTK para tokenizar una frase en español.
* Importa otro tokenizador de NLTK y utilízalo para tokenizar la misma frase en español.
* Utiliza un stemmer de NLTK para obtener la forma base de diferentes palabras en español.
* Utiliza un stemmer en inglés y compara los resultados con el stemmer en español.
* Importa otro stemmer de NLTK y utilízalo para obtener la forma base de diferentes palabras en español.
* Utiliza el lematizador de NLTK para obtener los lemas de diferentes palabras en inglés.
* Compara los resultados de la lematización con los resultados del stemming en inglés. ¿Por que son diferentes?